### ISSUE TITLE
Several of the sounds seem to crash the example project

### ISSUE THREAD

**Issue by subsoap** [britzl/blip#5] opened 2022-05-26 06:26 UTC
jump, explosion, laser all crash
clicking random seed also causes crashes

tested on Windows 11

**Comment by britzl** [comment] 2022-05-27 10:41
Duplicate of https://github.com/britzl/blip/issues/3

**Comment by britzl** [comment] 2022-05-27 12:54
Could you please share a stacktrace from a crash?

**Comment by subsoap** [comment] 2022-05-27 20:40
[Blip.zip](https://github.com/britzl/blip/files/8789609/Blip.zip) pdb in here
[_crash.zip](https://github.com/britzl/blip/files/8789608/_crash.zip)

>	ntdll.dll!RtlReportCriticalFailure()	Unknown
 	ntdll.dll!RtlpHeapHandleError()	Unknown
 	ntdll.dll!RtlpHpHeapHandleError()	Unknown
 	ntdll.dll!RtlpLogHeapFailure()	Unknown
 	ntdll.dll!RtlpFreeHeap()	Unknown
 	ntdll.dll!RtlpFreeHeapInternal()	Unknown
 	ntdll.dll!RtlFreeHeap()	Unknown
 	Blip.exe!_free_base(void * block) Line 105	C++
 	Blip.exe!Create(SfxrSound(*)(int) f, lua_State * L) Line 68	C++
 	Blip.exe!Jump(lua_State * L) Line 77	C++
 	[External Code]	
 	Blip.exe!dmScript::PCallInternal(lua_State * L, int nargs, int nresult, int in_error_handler) Line 1384	C++
 	Blip.exe!dmGameObject::HandleMessage(void * context, dmGameObject::ScriptInstance * script_instance, dmMessage::Message * message, int function_ref, bool is_callback, bool deref_function_ref) Line 328	C++
 	Blip.exe!dmGameObject::CompScriptOnMessage(const dmGameObject::ComponentOnMessageParams & params) Line 425	C++
 	Blip.exe!dmGameObject::DispatchMessagesFunction(dmMessage::Message * message, void * user_ptr) Line 2277	C++
 	Blip.exe!dmMessage::InternalDispatch(unsigned __int64 socket, void(*)(dmMessage::Message *, void *) dispatch_callback, void * user_ptr, bool blocking) Line 544	C++
 	Blip.exe!dmGameObject::DispatchMessages(dmGameObject::Collection * collection, unsigned __int64 * sockets, unsigned int socket_count) Line 2351	C++
 	Blip.exe!dmGameObject::Update(dmGameObject::Collection * collection, const dmGameObject::UpdateContext * update_context) Line 2515	C++
 	Blip.exe!dmEngine::StepFrame(dmEngine::Engine * engine, float dt) Line 1552	C++
 	[Inline Frame] Blip.exe!dmEngine::Step(dmEngine::Engine *) Lin

> e 1726	C++
 	Blip.exe!dmEngineUpdate(dmEngine::Engine * engine) Line 2060	C++
 	Blip.exe!dmEngine::RunLoop(const dmEngine::RunLoopParams * params) Line 83	C++
 	[Inline Frame] Blip.exe!EngineMain(int) Line 51	C++
 	Blip.exe!engine_main(int argc, char * * argv) Line 148	C++
 	[External Code]

**Comment by britzl** [comment] 2022-05-27 20:55
Thanks. I've pushed one fix to the main branch. Could you please give it a try?

**Comment by subsoap** [comment] 2022-05-27 23:29
Only crashes with Explosion now

No crash file is being generated though

```
	ntdll.dll!RtlReportCriticalFailure()	Unknown
 	ntdll.dll!RtlpHeapHandleError()	Unknown
 	ntdll.dll!RtlpHpHeapHandleError()	Unknown
 	ntdll.dll!RtlpLogHeapFailure()	Unknown
 	ntdll.dll!RtlpFreeHeap()	Unknown
 	ntdll.dll!RtlpFreeHeapInternal()	Unknown
 	ntdll.dll!RtlFreeHeap()	Unknown
 	Blip.exe!_free_base(void * block) Line 105	C++
 	Blip.exe!Create(SfxrSound(*)(int) f, lua_State * L) Line 72	C++
 	Blip.exe!Explosion(lua_State * L) Line 93	C++
 	[External Code]	
 	Blip.exe!dmScript::PCallInternal(lua_State * L, int nargs, int nresult, int in_error_handler) Line 1384	C++
 	Blip.exe!dmGameObject::HandleMessage(void * context, dmGameObject::ScriptInstance * script_instance, dmMessage::Message * message, int function_ref, bool is_callback, bool deref_function_ref) Line 328	C++
 	Blip.exe!dmGameObject::CompScriptOnMessage(const dmGameObject::ComponentOnMessageParams & params) Line 425	C++
 	Blip.exe!dmGameObject::DispatchMessagesFunction(dmMessage::Message * message, void * user_ptr) Line 2277	C++
 	Blip.exe!dmMessage::InternalDispatch(unsigned __int64 socket, void(*)(dmMessage::Message *, void *) dispatch_callback, void * user_ptr, bool blocking) Line 544	C++
 	Blip.exe!dmGameObject::DispatchMessages(dmGameObject::Collection * collection, unsigned __int64 * sockets, unsigned int socket_count) Line 2351	C++
 	Blip.exe!dmGameObject::Update(dmGameObject::Collection * collection, const dmGameObject::UpdateContext * update_context) Line 2515	C++
 	Blip.exe!dmEngine::StepFrame(dmEngine::Engine * engine, float dt) Line 1552	C++
 	[Inline Frame] Blip.exe!dmEngine::Step(dmEngine::Engine *) Line 1726	C++
 	Blip.exe!dmEngineUpdate(dmEngine::Engine * engine) Line 2060	C++
 	Blip.exe!dmEngine::RunLoop(const dmEngine::RunLoopParams * params) Line 83	C++
 	[Inline Frame] Blip.exe!EngineMain(int) Line 51	C++
 	Blip.exe!engine_main(int argc, char * * argv) Line 148	C++
 	[External Code]	
```

**Closed as completed** 2022-05-28 20:16 UTC
